using TextToSpeechServer.Protos;

namespace TextToSpeechServer
{
    public static class Utils
    {
        public static string GetHhMmSs()
        {
            return DateTime.Now.ToString("HH:mm:ss");
        }

        public static string GetDdMmYyyy()
        {
            return DateTime.Now.ToString("dd-MMM-yyyy");
        }

        public static readonly Dictionary<KokoroVoiceName, string> KokoroVoiceDict = new Dictionary<KokoroVoiceName, string>
    {
        {
            KokoroVoiceName.AfAlloy,
            "af_alloy"
        },
        {
            KokoroVoiceName.AfAoede,
            "af_aoede"
        },
        {
            KokoroVoiceName.AfBella,
            "af_bella"
        },
        {
            KokoroVoiceName.AfHeart,
            "af_heart"
        },
        {
            KokoroVoiceName.AfJessica,
            "af_jessica"
        },
        {
            KokoroVoiceName.AfKore,
            "af_kore"
        },
        {
            KokoroVoiceName.AfNicole,
            "af_nicole"
        },
        {
            KokoroVoiceName.AfNova,
            "af_nova"
        },
        {
            KokoroVoiceName.AfRiver,
            "af_river"
        },
        {
            KokoroVoiceName.AfSarah,
            "af_sarah"
        },
        {
            KokoroVoiceName.AfSky,
            "af_sky"
        },
        {
            KokoroVoiceName.AmAdam,
            "am_adam"
        },
        {
            KokoroVoiceName.AmEcho,
            "am_echo"
        },
        {
            KokoroVoiceName.AmEric,
            "am_eric"
        },
        {
            KokoroVoiceName.AmFenrir,
            "am_fenrir"
        },
        {
            KokoroVoiceName.AmLiam,
            "am_liam"
        },
        {
            KokoroVoiceName.AmMichael,
            "am_michael"
        },
        {
            KokoroVoiceName.AmOnyx,
            "am_onyx"
        },
        {
            KokoroVoiceName.AmPuck,
            "am_puck"
        },
        {
            KokoroVoiceName.AmSanta,
            "am_santa"
        },
        {
            KokoroVoiceName.BfAlice,
            "bf_alice"
        },
        {
            KokoroVoiceName.BfEmma,
            "bf_emma"
        },
        {
            KokoroVoiceName.BfIsabella,
            "bf_isabella"
        },
        {
            KokoroVoiceName.BfLily,
            "bf_lily"
        },
        {
            KokoroVoiceName.BmDaniel,
            "bm_daniel"
        },
        {
            KokoroVoiceName.BmFable,
            "bm_fable"
        },
        {
            KokoroVoiceName.BmGeorge,
            "bm_george"
        },
        {
            KokoroVoiceName.BmLewis,
            "bm_lewis"
        },
        {
            KokoroVoiceName.EfDora,
            "ef_dora"
        },
        {
            KokoroVoiceName.EmAlex,
            "em_alex"
        },
        {
            KokoroVoiceName.EmSanta,
            "em_santa"
        },
        {
            KokoroVoiceName.FfSiwis,
            "ff_siwis"
        },
        {
            KokoroVoiceName.HfAlpha,
            "hf_alpha"
        },
        {
            KokoroVoiceName.HfBeta,
            "hf_beta"
        },
        {
            KokoroVoiceName.HmOmega,
            "hm_omega"
        },
        {
            KokoroVoiceName.HmPsi,
            "hm_psi"
        },
        {
            KokoroVoiceName.IfSara,
            "if_sara"
        },
        {
            KokoroVoiceName.ImNicola,
            "im_nicola"
        },
        {
            KokoroVoiceName.JfAlpha,
            "jf_alpha"
        },
        {
            KokoroVoiceName.JfGongitsune,
            "jf_gongitsune"
        },
        {
            KokoroVoiceName.JfNezumi,
            "jf_nezumi"
        },
        {
            KokoroVoiceName.JfTebukuro,
            "jf_tebukuro"
        },
        {
            KokoroVoiceName.JmKumo,
            "jm_kumo"
        },
        {
            KokoroVoiceName.PfDora,
            "pf_dora"
        },
        {
            KokoroVoiceName.PmAlex,
            "pm_alex"
        },
        {
            KokoroVoiceName.PmSanta,
            "pm_santa"
        },
        {
            KokoroVoiceName.ZfXiaobei,
            "zf_xiaobei"
        },
        {
            KokoroVoiceName.ZfXiaoni,
            "zf_xiaoni"
        },
        {
            KokoroVoiceName.ZfXiaoxiao,
            "zf_xiaoxiao"
        },
        {
            KokoroVoiceName.ZfXiaoyi,
            "zf_xiaoyi"
        }
    };
    }
}
